### ISSUE TITLE
Better color parsing 

### ISSUE THREAD

**Issue by okonet** [sh-waqar/stylelint-declaration-use-variable#16]
Assume following example:

```css
.test {
  border-top: 1px solid #e8eae8;
  background: #fff;
}
```

and following config:

```
"sh-waqar/declaration-use-variable": [
      [
        "/color/",
        "/background/",
        "/border/"
      ]
    ]
```

Right now I'm getting `Expected variable for "border-top".` but I'd really like to enforce using a variable for the color and not for the whole declaration. This isn't possible with the shorthand syntax at the moment.

**Comment by okonet** [comment]
Some declarations also might have shorthand syntax:

```css
border-color: #767676 transparent transparent;
```

In this case I'd expect only the hex color to be a variable.

**Comment by okonet** [comment]
It looks like this will require parsing of the values. #14 seems also related.

**Comment by AndyOGo** [comment]
@okonet 
I'm keen for this feature too. Though it's ambiguous to specify `border` shorthand.
It could mean one of the following:

- A `$valiable` specifying all three properties, like:
  ````scss
  $border: 1px solid #fff;

  .foo { border: $border; }
  ````
- Or multiple `$variables` specifying each property, like:
````scss
  $border-width: 1px:
  $border-style: solid;
  $border-color: #fff;

  .foo { border: $border-width $border-style $border-color; }
  ````
- or any other possible shorthand combination
