### ISSUE TITLE
Consider ignoring `inherit`

### ISSUE THREAD

**Issue by amk221** [sh-waqar/stylelint-declaration-use-variable#22]
```css
.my-parent {
  color: $brand-red;
}

.my-child {
  color: inherit;
}
```
