### ISSUE TITLE
Support for css-loader @values?

### ISSUE THREAD

**Issue by mpelzsherman** [sh-waqar/stylelint-declaration-use-variable#35]
We're using [css-loader](https://www.npmjs.com/package/css-loader#values) on our project, which allows us to defined variables like so:

```css
@value foo: #BF4040;
 
.header {
  color: foo;
}
```

Using this "out of the box" with no special config, it's flagging all of our @value-defined variables as rule violations.

Is there any way to get this working, or would this be a new feature?
